name: Polenta
version: 1.3.10
date: 2022-03-29
description: |
    Polycyclic presentations for matrix groups

authors:
    - name: Björn Assmann

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.7"

needed-pkgs:
    - name: "polycyclic"
      version: "2.10.1"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "alnuth"
      version: "2.2.3"
      url: "https://gap-packages.github.io/alnuth"
    - name: "radiroot"
      version: "2.4"
      url: "https://gap-packages.github.io/radiroot/"

suggested-pkgs:
    - name: "aclib"
      version: "1.0"
      url: "https://gap-packages.github.io/aclib/"

www: https://gap-packages.github.io/polenta/
readme: README.md
packageinfo: https://gap-packages.github.io/polenta/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/polenta/releases/download/v1.3.10/polenta-1.3.10.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/polenta/releases/download/v1.3.10/polenta-1.3.10.tar.bz2

abstract: |
    The <span class="pkgname">Polenta</span> package provides  methods to compute polycyclic presentations of matrix groups (finite or infinite). As a by-product, this package gives some functionality to compute certain module series for modules of solvable groups. For example, if G is a rational polycyclic matrix group, then we can compute the radical series of the natural Q[G]-module Q^d.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
