#!/bin/sh

GAPROOT=../../..
GAP=$GAPROOT/bin/gap.sh

$GAP -A -q -T <<GAPDOC_SCRIPT
LoadPackage("gapdoc");;
MakeGAPDocDoc( ".", "main", [ ], "polenta", "$GAPROOT", "MathJax" );;
CopyHTMLStyleFiles(".");
GAPDOC_SCRIPT
